### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by slaygirlz** [boyphongsakorn/playitgg-docker#1]
how to run this container?

**Comment by boyphongsakorn** [comment]
> how to run this container?

first you need to run [playit.exe](https://playit.gg/downloads/playit-0.8.3-beta-signed.exe) and find playit.toml

after that you need to fork this repository and copy or edit playit.toml from your find in playit.exe to your fork repo and build your Docker image own

but i have a plan to set playit.toml in environment variables

**Comment by slaygirlz** [comment]
oh i thought it was a simple command it will be nice if the project had a video

**Comment by boyphongsakorn** [comment]
> oh i thought it was a simple command it will be nice if the project had a video

after i dev playit.toml in environment variables, i have a plan to make video about it.

**Comment by slaygirlz** [comment]
alr
